name: Sync Repositories

on: 
  push:
    branches:
      - main 

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Push to secondary repo
        run: |
          git remote add secondary https://MarcDIW:${{ secrets.SECON_REPO_SYNC }}@github.com/MarcDIW/Actividades.git
          git push --mirror secondary
